### ISSUE TITLE
Adding a button for a new Block

### ISSUE THREAD

**Issue by Hego2017** [youknowriad/gutenberg-vue#1]
Hi!

I am using your work for add Gutenbert to a CMS using Vue.js in Frontend.
I added a button for new Block. 
I tried a lot of ways for do it, finally I used the easy way, however I am sure to there is other way for do it. 

My code is: 

      `newBlock() {

            post.content.raw = []
            let htmlCollection = document.getElementsByClassName('blocks-editable__tinymce mce-content-body')
        
            let elements = Array.prototype.slice.call( htmlCollection )

            elements.forEach((e) => {
                let block = document.getElementById(e.id)

                if (block !== undefined && block !== null) {
                    post.content.raw += [
                    '',
                    block.textContent,
                    '',
                    ].join('')
                } 
            });

            post.content.raw += [
                '',
                '<p>New Block. You can start to write</p>',
                '',
                ].join('')

            this.$store.commit('resetBlocks', parse(post.content.raw));
        },`

**Comment by youknowriad** [comment]
I'm sorry can't help too much, this repository is a very old experiment. we went o n a different direction (React app). If you want to use Gutenberg on a vue project, I'd personally wrap the React version instead.

Good luck
